# Felix Baseline CatBoost Notebook

This is a baseline CatBoost workflow that demonstrates the core portfolio_toolkit pattern.

## Workflow Summary

1. Load shared dataset (shared_set_2)
2. Build features: shared toolkit features + 1 custom feature
3. Create targets
4. Train CatBoost model for expected returns
5. Generate predictions
6. Convert to portfolio weights
7. Run shared backtest
8. Log results to MLflow

In [1]:
# Setup and imports
from pathlib import Path
import numpy as np
import pandas as pd

from portfolio_toolkit import (
    build_features,
    build_metrics,
    get_dataset_spec,
    init_mlflow,
    load_prices,
    log_backtest,
    log_portfolio,
    log_predictions,
    make_forward_return_target,
    slice_split,
    split_dates,
    start_run,
    validate_prediction_frame,
    validate_weights_frame,
    weights_from_predictions_risk_adjusted,
    backtest_weights,
    write_backtest_artifacts,
)

print('Imports loaded successfully.')

/Users/beizhang/Portfolio-Optimization-Lib/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Imports loaded successfully.

In [3]:
# Configuration
# Find repo root by looking for configs/datasets.toml
from pathlib import Path
import sys

current_dir = Path.cwd()
repo_root = None

# Walk up the directory tree to find repo_root
for parent in [current_dir] + list(current_dir.parents):
    if (parent / 'configs' / 'datasets.toml').exists():
        repo_root = parent
        break

if repo_root is None:
    raise FileNotFoundError("Could not find repo_root. Make sure you run this from the Portfolio-Optimization-Lib repo.")

dataset_name = 'shared_set_2'
model_name = 'felix_baseline_catboost'
horizon = 5
output_dir = repo_root / 'runs' / 'felix_baseline_catboost'
output_dir.mkdir(parents=True, exist_ok=True)

spec = get_dataset_spec(dataset_name, repo_root=repo_root)
splits = split_dates(dataset_name, repo_root=repo_root)

print('Repo root:', repo_root)
print('Dataset preset:', dataset_name)
print('Dataset name:', spec.name)
print('Tickers:', len(spec.tickers))
print('Splits:', splits)

Repo root: /Users/beizhang/Portfolio-Optimization-Lib
Dataset preset: shared_set_2
Dataset name: growth_tech_innovation
Tickers: 26
Splits: {'train': (Timestamp('2014-01-02 00:00:00'), Timestamp('2019-12-31 00:00:00')), 'val': (Timestamp('2020-01-02 00:00:00'), Timestamp('2021-12-31 00:00:00')), 'test': (Timestamp('2022-01-03 00:00:00'), Timestamp('2025-12-31 00:00:00'))}

## 1. Load Shared Price Data

In [4]:
prices = load_prices(dataset_name, repo_root=repo_root)

print('Price frame shape:', prices.shape)
print('Date range:', prices['date'].min(), '->', prices['date'].max())
print('Unique tickers:', prices['ticker'].nunique())
display(prices.head())

Price frame shape: (78468, 8)
Date range: 2014-01-02 00:00:00 -> 2025-12-31 00:00:00
Unique tickers: 26

,date,ticker,open,high,low,close,adj_close,volume
0,2014-01-02,AAPL,19.845715,19.893929,19.715000,19.754642,17.140659,234684800
1,2014-01-03,AAPL,19.745001,19.775000,19.301071,19.320715,16.764149,392467600
2,2014-01-06,AAPL,19.194643,19.528570,19.057142,19.426071,16.855572,412610800
3,2014-01-07,AAPL,19.440001,19.498571,19.211430,19.287144,16.735027,317209200
4,2014-01-08,AAPL,19.243214,19.484285,19.238930,19.409286,16.841009,258529600

## 2. Build Features: Shared + Custom

In [5]:
# Build shared baseline features
base_feature_names = [
    'return_5d',
    'return_20d',
    'vol_20d',
    'momentum_20d',
    'momentum_60d',
    'rsi_14',
    'price_to_sma_20d',
    'price_to_sma_50d',
    'volume_zscore_20d',
    'excess_return_20d_vs_spy',
]

features = build_features(prices, feature_names=base_feature_names)
print('Base feature frame shape:', features.shape)
display(features.head())

Base feature frame shape: (78468, 12)

,date,ticker,return_5d,return_20d,vol_20d,momentum_20d,momentum_60d,rsi_14,price_to_sma_20d,price_to_sma_50d,volume_zscore_20d,excess_return_20d_vs_spy
0,2014-01-02,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-01-03,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-01-06,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-01-07,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-01-08,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Add one custom notebook-local feature
# momentum_vol_ratio: captures risk-adjusted trend strength
eps = 1e-6
features['momentum_vol_ratio'] = features['momentum_20d'] / (features['vol_20d'].abs() + eps)

feature_names = base_feature_names + ['momentum_vol_ratio']

print('Feature frame shape with custom feature:', features.shape)
print('Feature count:', len(feature_names))
display(features[['date', 'ticker', 'momentum_vol_ratio']].head())

Feature frame shape with custom feature: (78468, 13)
Feature count: 11

        date ticker  momentum_vol_ratio
0 2014-01-02   AAPL                 NaN
1 2014-01-03   AAPL                 NaN
2 2014-01-06   AAPL                 NaN
3 2014-01-07   AAPL                 NaN
4 2014-01-08   AAPL                 NaN

## 3. Build Targets

In [7]:
# Build forward return target only (baseline model)
targets = make_forward_return_target(prices, horizon=horizon)

# Merge features and targets
modeling_frame = features.merge(targets, on=['date', 'ticker'], how='left')

# Drop rows with missing values
modeling_frame = modeling_frame.replace([np.inf, -np.inf], np.nan).dropna().reset_index(drop=True)

target_col = f'forward_return_{horizon}d'

print('Modeling frame shape after dropping nulls:', modeling_frame.shape)
display(modeling_frame.head())

Modeling frame shape after dropping nulls: (76765, 14)

,date,ticker,return_5d,return_20d,vol_20d,momentum_20d,momentum_60d,rsi_14,price_to_sma_20d,price_to_sma_50d,volume_zscore_20d,excess_return_20d_vs_spy,momentum_vol_ratio,forward_return_5d
0,2014-03-31,AAPL,-0.004544,0.017016,0.006838,0.017016,-0.023823,50.700538,0.006098,0.014112,-1.268528,0.001579,2.488208,-0.024724
1,2014-04-01,AAPL,-0.006129,0.019595,0.006966,0.019595,0.007232,54.962510,0.014311,0.023226,-0.625223,0.011594,2.812653,-0.033619
2,2014-04-02,AAPL,0.005132,0.019141,0.006963,0.019141,0.003433,63.014063,0.015029,0.025053,-0.962614,0.008682,2.748570,-0.022542
3,2014-04-03,AAPL,0.002475,0.015148,0.007125,0.015148,0.003657,66.199215,0.007236,0.018312,-1.238125,0.008333,2.125688,-0.028415
4,2014-04-04,AAPL,-0.009388,0.002602,0.007726,0.002602,-0.015561,55.243543,-0.005921,0.005940,0.682547,0.008112,0.336719,-0.022959

## 4. Train/Val/Test Split and Standardization

In [8]:
# Use shared split functions
train = slice_split(modeling_frame, dataset_name, 'train', repo_root=repo_root)
val = slice_split(modeling_frame, dataset_name, 'val', repo_root=repo_root)
test = slice_split(modeling_frame, dataset_name, 'test', repo_root=repo_root)

print(f'Train: {len(train)} rows')
print(f'Val: {len(val)} rows')
print(f'Test: {len(test)} rows')

# Standardize using only train statistics
train_means = train[feature_names].mean()
train_stds = train[feature_names].std(ddof=0).replace(0.0, 1.0)

def standardize(df):
    return ((df[feature_names] - train_means) / train_stds).to_numpy(dtype=float)

X_train = standardize(train)
X_val = standardize(val)
X_test = standardize(test)

y_train = train[target_col].to_numpy(dtype=float)
y_val = val[target_col].to_numpy(dtype=float)

print(f'X_train shape: {X_train.shape}')
print(f'Feature count: {len(feature_names)}')

Train: 37695 rows
Val: 13130 rows
Test: 25940 rows
X_train shape: (37695, 11)
Feature count: 11

## 5. Train CatBoost Model

In [9]:
from catboost import CatBoostRegressor

# Train baseline CatBoost model
model = CatBoostRegressor(
    iterations=100,
    learning_rate=0.05,
    random_seed=42,
    verbose=False,
)

model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    early_stopping_rounds=20
)

val_mse = float(((model.predict(X_val) - y_val) ** 2).mean())
val_rmse = float(val_mse ** 0.5)

print(f'Validation MSE: {val_mse:.8f}')
print(f'Validation RMSE: {val_rmse:.8f}')

Validation MSE: 0.00307728
Validation RMSE: 0.05547321

## 6. Generate Predictions

In [10]:
# Generate test predictions
test_predictions = model.predict(X_test)

# Create standardized prediction frame
predictions = test.loc[:, ['date', 'ticker']].copy()
predictions['horizon'] = horizon
predictions['expected_return'] = test_predictions
predictions['uncertainty'] = val_rmse  # Use validation RMSE as uncertainty estimate

# Validate prediction frame
predictions = validate_prediction_frame(
    predictions,
    dataset_name=dataset_name,
    horizon=horizon,
    repo_root=repo_root,
)

print('Prediction frame shape:', predictions.shape)
display(predictions.head())

Prediction frame shape: (25940, 5)

        date ticker  horizon  expected_return  uncertainty
0 2022-01-03   AAPL        5         0.005140     0.055473
1 2022-01-03   ADBE        5         0.007009     0.055473
2 2022-01-03    ADI        5         0.004915     0.055473
3 2022-01-03   AMAT        5         0.006307     0.055473
4 2022-01-03    AMD        5         0.008148     0.055473

## 7. Convert to Portfolio Weights

In [11]:
# Use simple risk-adjusted weighting
# Clip expected_return to avoid extreme weights
predictions_clipped = predictions.copy()
predictions_clipped['expected_return'] = predictions_clipped['expected_return'].clip(-0.5, 0.5)

# Create a simple volatility estimate for weighting
predictions_clipped['expected_volatility'] = 0.15  # Fixed volatility baseline

# Generate portfolio weights
portfolio = weights_from_predictions_risk_adjusted(
    predictions_clipped,
    dataset_name=dataset_name,
    strategy_name=model_name,
)

# Validate weights
validated_weights = validate_weights_frame(
    portfolio.weights,
    dataset_name=dataset_name,
    repo_root=repo_root,
)

print('Strategy:', portfolio.strategy_name)
print('Weights frame shape:', validated_weights.shape)
display(validated_weights.head())

Strategy: felix_baseline_catboost
Weights frame shape: (998, 26)

,AAPL,ADBE,ADI,AMAT,AMD,AMZN,AVGO,CRM,CSCO,GOOGL,...,MU,NFLX,NOW,NVDA,ORCL,PANW,QCOM,SPY,TSLA,TXN
date,,,,,,,,,,,,,,,,,,,,,
2022-01-03,0.033094,0.045127,0.031649,0.040607,0.052460,0.028686,0.036564,0.022056,0.025575,0.029950,...,0.034568,0.024829,0.046693,0.064828,0.045466,0.051714,0.045654,0.026692,0.045789,0.029221
2022-01-04,0.035459,0.044297,0.031592,0.047585,0.051908,0.029316,0.032377,0.028593,0.027276,0.029863,...,0.034491,0.028495,0.049949,0.065929,0.047732,0.047779,0.043424,0.026633,0.026214,0.026961
2022-01-05,0.043130,0.066363,0.027332,0.041580,0.057127,0.024509,0.036787,0.100796,0.026705,0.022473,...,0.035270,0.000000,0.080890,0.010794,0.050051,0.045244,0.041720,0.025690,0.007836,0.021650
2022-01-06,0.040277,0.063282,0.025680,0.043854,0.054186,0.023825,0.035387,0.087650,0.023505,0.024661,...,0.029435,0.008043,0.067697,0.055832,0.047008,0.040881,0.037940,0.024497,0.014587,0.023482
2022-01-07,0.041215,0.074361,0.026704,0.041310,0.047672,0.021820,0.042316,0.084168,0.023406,0.025236,...,0.030505,0.011433,0.069273,0.000000,0.042653,0.041695,0.058079,0.025476,0.020385,0.022446

## 8. Run Shared Backtest

In [12]:
# Run the shared backtest
result = backtest_weights(dataset_name, portfolio, repo_root=repo_root)

# Build metrics
metrics = build_metrics(result)

# Write artifacts
artifact_paths = write_backtest_artifacts(result, output_dir)

print('Backtest completed successfully')
print('Metrics:')
for key, value in sorted(metrics.items()):
    print(f'  {key}: {value:.6f}')

Backtest completed successfully
Metrics:
  annual_return: 0.051002
  annual_volatility: 0.173452
  average_turnover: 0.059907
  benchmark_total_return: 0.507582
  calmar: 0.122244
  excess_return_vs_benchmark: 0.307150
  max_drawdown: -0.417211
  sharpe: 0.294040
  sortino: 0.248486
  total_return: 0.814732

## 9. Log to MLflow

In [13]:
import mlflow

mlflow_layout = init_mlflow(repo_root)
print('MLflow tracking URI:', mlflow_layout['tracking_uri'])

with start_run(
    run_name='Felix_Baseline_CatBoost',
    dataset_name=dataset_name,
    tags={
        'workflow': 'felix_baseline',
        'model_family': 'catboost',
        'prediction_horizon': str(horizon),
    },
    repo_root=repo_root,
):
    mlflow.log_params({
        'model_name': model_name,
        'dataset_name': dataset_name,
        'horizon': horizon,
        'feature_count': len(feature_names),
        'catboost_iterations': 100,
        'catboost_lr': 0.05,
        'catboost_seed': 42,
        'custom_features': 'momentum_vol_ratio',
    })
    
    mlflow.log_metrics({
        'val_mse': val_mse,
        'val_rmse': val_rmse,
    })
    
    log_predictions(predictions)
    log_portfolio(portfolio)
    log_backtest(result)

print('MLflow run Felix_Baseline_CatBoost logged successfully')

MLflow tracking URI: https://adams-macbook-pro.tail5ddc35.ts.net
🏃 View run Felix_Baseline_CatBoost at: https://adams-macbook-pro.tail5ddc35.ts.net/#/experiments/1/runs/b9903e72f0b6402595bf6a970916aaea
🧪 View experiment at: https://adams-macbook-pro.tail5ddc35.ts.net/#/experiments/1
MLflow run Felix_Baseline_CatBoost logged successfully

## 10. Results Summary

In [14]:
print('=== BASELINE CATBOOST RESULTS ===')
print()
print('Model Performance:')
for key, value in sorted(metrics.items()):
    print(f'  {key}: {value:.6f}')

print()
print('Backtest Output:')
display(result.nav.tail().to_frame('nav'))
display(result.returns.tail().to_frame('returns'))
display(result.turnover.tail().to_frame('turnover'))

print()
print('Artifacts:')
for key, path in artifact_paths.items():
    print(f'  {key}: {path}')

=== BASELINE CATBOOST RESULTS ===

Model Performance:
  annual_return: 0.051002
  annual_volatility: 0.173452
  average_turnover: 0.059907
  benchmark_total_return: 0.507582
  calmar: 0.122244
  excess_return_vs_benchmark: 0.307150
  max_drawdown: -0.417211
  sharpe: 0.294040
  sortino: 0.248486
  total_return: 0.814732

Backtest Output:

                   nav
2025-12-24  183.860358
2025-12-26  184.065068
2025-12-29  183.461666
2025-12-30  183.254501
2025-12-31  181.473191

             returns
2025-12-24  0.002971
2025-12-26  0.001113
2025-12-29 -0.003278
2025-12-30 -0.001129
2025-12-31 -0.009720

            turnover
date
2025-12-17  0.090974
2025-12-18  0.038228
2025-12-19  0.089822
2025-12-22  0.046997
2025-12-23  0.038728

Artifacts:
  weights: /Users/beizhang/Portfolio-Optimization-Lib/runs/felix_baseline_catboost/weights.parquet
  nav: /Users/beizhang/Portfolio-Optimization-Lib/runs/felix_baseline_catboost/nav.parquet
  returns: /Users/beizhang/Portfolio-Optimization-Lib/runs/felix_baseline_catboost/returns.parquet
  turnover: /Users/beizhang/Portfolio-Optimization-Lib/runs/felix_baseline_catboost/turnover.parquet
  benchmarks: /Users/beizhang/Portfolio-Optimization-Lib/runs/felix_baseline_catboost/benchmarks.parquet
  metrics: /Users/beizhang/Portfolio-Optimization-Lib/runs/felix_baseline_catboost/metrics.json
  metrics_table: /Users/beizhang/Portfolio-Optimization-Lib/runs/felix_baseline_catboost/metrics_table.parquet
  quantstats_report: /Users/beizhang/Portfolio-Optimization-Lib/runs/felix_baseline_catboost/quantstats.html

In [15]:
# Final validation
assert 'sharpe' in result.metrics, 'Sharpe ratio not computed'
assert 'max_drawdown' in result.metrics, 'Max drawdown not computed'
assert (validated_weights.sum(axis=1).round(6) == 1.0).all(), 'Weights do not sum to 1.0'
assert len(predictions) > 0, 'No predictions generated'
print('✓ All validations passed')
print('✓ Baseline CatBoost workflow completed successfully')

✓ All validations passed
✓ Baseline CatBoost workflow completed successfully